# -*- coding: utf-8 -*-
"""Official feature coverage map for the release verification tests.

Sources include https://drissionpage.cn/features/4.2/ and
https://drissionpage.cn/features/4.1/, and https://drissionpage.cn/features/4/.
The map is intentionally explicit so the runner can report what is covered by
local deterministic test cases and what is intentionally outside the default batch.
"""
from __future__ import annotations

FEATURES = [
    {"id": "chromium_entrypoint", "title": "推荐使用 Chromium 代替 ChromiumPage", "case": "api_surface"},
    {"id": "context_isolation", "title": "独立 BrowserContext、cookies 和标签页方法", "case": "context_isolation"},
    {"id": "cross_origin_iframe_element", "title": "跨域 iframe 内元素直接获取（非截图）", "case": "iframe_non_screenshot"},
    {"id": "cross_origin_iframe_listener", "title": "跨域 iframe 数据包监听（非截图）", "case": "iframe_non_screenshot"},
    {"id": "listener_setters", "title": "listen.set_method / listen.set_res_type API", "case": "listener_ws_sse"},
    {"id": "websocket_packet", "title": "WebSocketPacket 监听与字段", "case": "listener_ws_sse"},
    {"id": "sse_packet", "title": "SSEPacket 监听与字段", "case": "listener_ws_sse"},
    {"id": "proxy_auth", "title": "账密形式代理设置", "case": "api_surface"},
    {"id": "nav_result", "title": "get() 返回 NavResult 状态信息", "case": "navigation_result"},
    {"id": "remove_test_type", "title": "ChromiumOptions.remove_test_type()", "case": "api_surface"},
    {"id": "edge_path", "title": "set_browser_path(edge=True)", "case": "api_surface"},
    {"id": "user_data_logic", "title": "用户文件夹设置逻辑", "case": "api_surface"},
    {"id": "disable_pdf_preview", "title": "disable_pdf_preview()", "case": "api_surface"},
    {"id": "download_by_browser", "title": "download.by_browser() 主动下载", "case": "download_browser"},
    {"id": "permissions", "title": "浏览器/上下文权限设置", "case": "context_isolation"},
    {"id": "ax_locator", "title": "ax: 无障碍定位", "case": "locator_behavior"},
    {"id": "auto_locator", "title": "无前缀自动匹配 xpath/css/text", "case": "locator_behavior"},
    {"id": "tab_no_text_str", "title": "Tab.ele() 不再返回 str 文本节点", "case": "locator_behavior"},
    {"id": "show_trail", "title": "显示鼠标轨迹 set.show_trail()", "case": "api_surface"},
    {"id": "console_listener", "title": "console 监听结果更全面", "case": "console_and_tabs"},
    {"id": "hidden_tab", "title": "Chromium.new_tab(hidden=True)", "case": "console_and_tabs"},
    {"id": "get_tab_as_id", "title": "Chromium.get_tab(as_id=True)", "case": "console_and_tabs"},
    {"id": "tab_activate", "title": "ChromiumTab.activate()", "case": "console_and_tabs"},
    {"id": "drag_in_offsets", "title": "ChromiumTab.drag_in(offset_x/offset_y)", "case": "api_surface"},
    {"id": "new_ele", "title": "ChromiumTab.new_ele()", "case": "api_surface"},
    {"id": "upload_timeout", "title": "wait.upload_paths_inputted(timeout)", "case": "api_surface"},
    {"id": "get_raise_err", "title": "get(show_errmsg -> raise_err)", "case": "navigation_result"},
    {"id": "click_defaults", "title": "click() 随机位置且 wait_stop 默认 False", "case": "api_surface"},
    {"id": "download_file_exists", "title": "click.to_download(file_exists)", "case": "api_surface"},
    {"id": "css_selector", "title": "css_path 改名 css_selector / 数字开头 id 修复", "case": "locator_behavior"},
    {"id": "wait_clickable_wait_stop", "title": "wait.clickable(wait_stop)", "case": "api_surface"},
    {"id": "check_checked", "title": "check(checked=True)", "case": "locator_behavior"},
    {"id": "settings_wait_stop", "title": "Settings.wait_stop_before_click", "case": "api_surface"},
    {"id": "actions_key_tuple", "title": "Mac 按键元组组合兼容", "case": "api_surface"},
    {"id": "session_timeout", "title": "SessionPage get/post timeout 生效", "case": "session_timeout"},
    {"id": "listener_restart", "title": "监听 stop() 后 start() 生效", "case": "listener_ws_sse"},
    {"id": "alert_on_open", "title": "打开即 alert 页面不卡住", "case": "alert_on_open"},
    {"id": "iframe_waits", "title": "iframe wait.title_change/url_change（非截图）", "case": "iframe_non_screenshot"},
    {"id": "builtin_listener", "title": "页面对象内置 listen.start/wait/stop 抓包", "case": "feature_listener_basics"},
    {"id": "listener_wait_silent", "title": "listen.wait_silent() 等待网络静默", "case": "feature_listener_basics"},
    {"id": "navigation_load_mode_none", "title": "none 加载模式不阻塞可用 DOM", "case": "feature_navigation_basics"},
    {"id": "navigation_timeout", "title": "get(timeout) 覆盖慢连接过程", "case": "feature_navigation_basics"},
    {"id": "session_local_file", "title": "SessionPage.get() 支持本地文件", "case": "feature_navigation_basics"},
    {"id": "download_management", "title": "set.download_path/download_file_name/wait.download_begin 下载管理", "case": "feature_download_management"},
    {"id": "page_object_actions_states_waits", "title": "页面对象 actions、states、wait.doc_loaded/title/url/eles_loaded", "case": "feature_page_object_basics"},
    {"id": "frame_rect_query", "title": "ChromiumFrame rect/states 和 frame DOM 查询", "case": "feature_page_object_basics"},
    {"id": "init_js_blocked_urls", "title": "add_init_js/remove_init_js 与 set.blocked_urls()", "case": "feature_page_object_basics"},
    {"id": "cookie_setters", "title": "set.cookies 单项设置、remove、clear", "case": "feature_cookie_setters"},
    {"id": "tab_management", "title": "new_tab(background)、get_tab(index/id)、Tab.close()", "case": "feature_tab_management"},
    {"id": "tab_alert", "title": "Tab.handle_alert() 与 states.has_alert", "case": "feature_tab_management"},
    {"id": "element_negative_relative", "title": "@! 否定定位与相对定位简化参数", "case": "feature_element_core_behaviors"},
    {"id": "element_rect_states", "title": "元素 rect、states.has_rect/is_whole_in_viewport、wait.has_rect", "case": "feature_element_core_behaviors"},
    {"id": "element_input_select_none", "title": "input(by_js)、check、select.by_option、NoneElement_value", "case": "feature_element_core_behaviors"},
    {"id": "options_settings", "title": "ChromiumOptions/SessionOptions/Settings 当前配置契约", "case": "feature_options_settings"},
    {"id": "chromium_object_tabs", "title": "Chromium 对象连接、标签页和浏览器操作", "case": "feature_chromium_tab_management"},
    {"id": "find_api", "title": "find() 多定位符真实查找", "case": "feature_find_api"},
    {"id": "console_property", "title": "页面对象 console 属性读取控制台信息", "case": "feature_console_and_cookie_formats"},
    {"id": "frame_setters_link", "title": "Frame/元素 set.property、set.style、link、get_frame 行为", "case": "feature_frame_shadow_setters"},
    {"id": "cookies_list_formats", "title": "cookies() as_dict/as_json/as_str 行为", "case": "feature_console_and_cookie_formats"},
    {"id": "session_snapshot_timeout", "title": "浏览器对象 s_ele/s_eles timeout 参数真实查询", "case": "feature_find_api"},
    {"id": "scroll_and_waits", "title": "scroll() 和 wait 新增参数/行为", "case": "feature_scroll_and_waits"},
    {"id": "element_multi_click", "title": "元素 click.multi(times) 多击/双击语义", "case": "feature_element_multi_click"},
    {"id": "shadow_root", "title": "shadow_root 等待并查询 shadow DOM", "case": "feature_frame_shadow_setters"},
    {"id": "tab_post_response", "title": "MixTab/ChromiumTab post() 返回 Response 对象", "case": "feature_tab_post_response"},
    {"id": "chromium_options_environment", "title": "ChromiumOptions.new_env/is_headless/auto_port(scope) 行为", "case": "feature_chromium_options_environment"},
    {"id": "ssr_site_smoke", "title": "可选 Astro SSR fixture 远端冒烟", "case": "feature_ssr_site_smoke"},
    {"id": "ssr_marketplace_flow", "title": "SSR Marketplace 浏览到下单完整业务流", "case": "feature_ssr_marketplace_flow"},
    {"id": "ssr_social_notes_mobile", "title": "SSR 社区笔记移动端瀑布流与互动", "case": "feature_ssr_social_notes_mobile"},
]

EXCLUDED = [
    {"id": "iframe_screenshot", "title": "iframe 元素截图/OOPIF 截图", "reason": "需要截图专项套件，默认发布验证批次不覆盖"},
    {"id": "recording_h265", "title": "录像 H.265 编码", "reason": "录屏编码依赖浏览器/系统媒体能力，需单独媒体专项验证"},
    {"id": "real_proxy", "title": "真实代理认证链路", "reason": "默认批次不依赖外部代理服务；仅覆盖代理配置解析和上下文参数"},
    {"id": "actions_pointer_times", "title": "动作链真实鼠标 click(times) 指针事件", "reason": "headless 指针事件易受浏览器窗口/焦点影响，默认批次用元素 click.multi() 覆盖稳定点击行为，动作链指针事件需专项验证"},
]
