# -*- coding:utf-8 -*-
"""
@Author   : g1879
@Contact  : g1879@qq.com
@Website  : https://DrissionPage.cn
@Copyright: (c) 2020 by g1879, Inc. All Rights Reserved.
"""
from queue import Queue
from typing import Union, List, Iterable, Optional, Literal, Any, Dict, Tuple

from requests.structures import CaseInsensitiveDict

from .._browsers.chromium import Chromium
from .._pages.chromium_base import ChromiumBase
from .._pages.chromium_frame import ChromiumFrame

__RES_TYPE__ = Literal['Document', 'Stylesheet', 'Image', 'Media', 'Font', 'Script', 'TextTrack', 'XHR', 'Fetch',
'Prefetch', 'EventSource', 'WebSocket', 'Manifest', 'SignedExchange', 'Ping', 'CSPViolationReport', 'Preflight', 'Other']


class BaseListener(object):
    listening: bool = ...
    _urls: Union[str, dict, True, None] = ...
    _is_regex: bool = ...
    _method: Union[set, True] = ...
    _res_type: Union[set, True] = ...
    _method_setter: Optional[MethodSetter] = ...
    _res_type_setter: Optional[ResTypeSetter] = ...

    def __init__(self, owner): ...

    @property
    def urls(self) -> Optional[set]:
        """返回监听目标"""
        ...

    @property
    def set_method(self) -> MethodSetter:
        """返回用于设置监听method类型的对象"""
        ...

    @property
    def set_res_type(self) -> ResTypeSetter:
        """返回用于设置监听ResourceType的对象"""
        ...

    def set_urls(self,
                 urls: Union[str, list, tuple, set, bool, None] = True,
                 is_regex: Optional[bool] = False) -> None:
        """指定要等待的数据包
        :param urls: 要匹配的数据包url特征，可用list等传入多个，为True时获取所有
        :param is_regex: 设置的target是否正则表达式
        :return: None
        """
        ...

    def start(self,
              urls: Union[str, list, tuple, set, bool, None] = None,
              is_regex: Optional[bool] = None) -> None:
        """拦截目标请求，每次拦截前清空结果
        :param urls: 要匹配的数据包url特征，可用list等传入多个，为True时获取所有
        :param is_regex: 设置的target是否正则表达式，为None时保持原来设置
        :return: None
        """
        ...

    def resume(self) -> None:
        """开始监听"""
        ...

    def _init_callback(self) -> None:
        """设置处理动作的方法"""
        ...

    def stop(self) -> None:
        """停止监听，清空已监听到的列表，释放资源"""
        ...

    def pause(self, clear: bool = True) -> None:
        """暂停监听
        :param clear: 是否清空已获取队列
        :return: None
        """
        ...

    def clear(self) -> None:
        """清空监听到但还没返回的结果"""
        ...


class Listener(BaseListener):
    _owner: ChromiumBase = ...
    _caught: Optional[Queue] = ...
    _extra_info_ids: Optional[dict] = ...
    _running_requests: int = ...
    _running_targets: int = ...
    _request_ids: Optional[Dict[str, DataPacket]] = ...
    _ws_info: Dict[str, WebSocketConnectInfo] = ...

    def __init__(self, owner: ChromiumBase):
        """
        :param owner: 页面对象
        """
        ...

    def wait(self,
             count: int = 1,
             timeout: float = None,
             fit_count: bool = True,
             raise_err: bool = None) -> Union[List[DataPacket], DataPacket,
    List[WebSocketPacket], WebSocketPacket, List[SSEPacket], SSEPacket, None]:
        """等待符合要求的数据包到达指定数量
        :param count: 需要捕捉的数据包数量
        :param timeout: 超时时间（秒），为None无限等待
        :param fit_count: 是否必须满足总数要求，发生超时，为True返回False，为False返回已捕捉到的数据包
        :param raise_err: 超时时是否抛出错误，为None时根据Settings设置
        :return: count为1时返回数据包对象，大于1时返回列表，超时且fit_count为True时返回False
        """
        ...

    def browser_wait(self,
                     count: int = 1,
                     timeout: float = None,
                     fit_count: bool = True,
                     raise_err: bool = None) -> Union[List[BrowserDataPacket], BrowserDataPacket, None]:
        """等待符合要求的数据包到达指定数量
        :param count: 需要捕捉的数据包数量
        :param timeout: 超时时间（秒），为None无限等待
        :param fit_count: 是否必须满足总数要求，发生超时，为True返回False，为False返回已捕捉到的数据包
        :param raise_err: 超时时是否抛出错误，为None时根据Settings设置
        :return: count为1时返回数据包对象，大于1时返回列表，超时且fit_count为True时返回False
        """
        ...

    def steps(self,
              count: int = None,
              timeout: float = None,
              gap=1) -> Iterable[
        Union[DataPacket, WebSocketPacket, SSEPacket, List[DataPacket], List[WebSocketPacket], List[SSEPacket]]]:
        """用于单步操作，可实现每收到若干个数据包执行一步操作（如翻页）
        :param count: 需捕获的数据包总数，为None表示无限
        :param timeout: 每个数据包等待时间（秒），为None表示无限
        :param gap: 每接收到多少个数据包返回一次数据
        :return: 用于在接收到监听目标时触发动作的可迭代对象
        """
        ...

    def browser_steps(self,
                      count: int = None,
                      timeout: float = None,
                      gap=1) -> Iterable[Union[BrowserDataPacket, List[BrowserDataPacket]]]:
        """用于单步操作，可实现每收到若干个数据包执行一步操作（如翻页）
        :param count: 需捕获的数据包总数，为None表示无限
        :param timeout: 每个数据包等待时间（秒），为None表示无限
        :param gap: 每接收到多少个数据包返回一次数据
        :return: 用于在接收到监听目标时触发动作的可迭代对象
        """
        ...

    def wait_silent(self,
                    timeout: float = None,
                    targets_only: bool = False,
                    limit: int = 0) -> bool:
        """等待所有请求结束
        :param timeout: 超时时间（秒），为None时无限等待
        :param targets_only: 是否只等待targets指定的请求结束
        :param limit: 剩下多少个连接时视为结束
        :return: 返回是否等待成功
        """
        ...

    def _to_target(self, target_id: str, owner: ChromiumBase) -> None:
        """切换监听的页面对象
        :param target_id: 新页面对象_target_id
        :param owner: 新页面对象
        :return: None
        """
        ...

    def _init_callback(self) -> None: ...

    def _eventSourceMessageReceived(self, **kwargs) -> None: ...

    def _webSocketFrameSent(self, **kwargs) -> None: ...

    def _webSocketFrameReceived(self, **kwargs) -> None: ...

    def _webSocketCreated(self, **kwargs) -> None: ...

    def _webSocketClosed(self, **kwargs) -> None: ...

    def _webSocketHandshakeResponseReceived(self, **kwargs) -> None: ...

    def _webSocketWillSendHandshakeRequest(self, **kwargs) -> None: ...

    def _requestWillBeSent(self, **kwargs) -> None: ...

    def _requestWillBeSentExtraInfo(self, **kwargs) -> None: ...

    def _response_received(self, **kwargs) -> None: ...

    def _responseReceivedExtraInfo(self, **kwargs) -> None: ...

    def _loading_finished_sse(self, **kwargs) -> Optional[DataPacket]: ...

    def _loading_failed_sse(self, **kwargs) -> Optional[DataPacket]: ...

    def _loading_finished(self, **kwargs) -> None: ...

    def _loading_failed(self, **kwargs) -> None: ...


class BrowserListener(BaseListener):
    _owner: Chromium = ...
    _caught: Dict[str, Queue] = ...
    _request_ids: Dict[str, BrowserDataPacket] = ...

    def __init__(self, owner: Chromium): ...

    def _init_callback(self) -> None: ...

    def _onRequestPaused(self, **kwargs) -> None: ...


def in_targets(listener: BaseListener,
               url: str, method: Union[True, str],
               res_type: Union[True, str]) -> Union[False, Tuple[Union[True, str], Union[True, str], Union[True, str]]]:
    """返回url是否命中targets
    :param listener: BaseListener对象
    :param url: url
    :param method: 连接类型
    :param res_type: 资源类型
    :return: 匹配到的监听目标
    """
    ...


class FrameListener(Listener):
    _owner: ChromiumFrame = ...
    _is_diff: bool = ...

    def __init__(self, owner: ChromiumFrame):
        """
        :param owner: ChromiumFrame对象
        """
        ...


class DataPacket(object):
    """数据包类"""
    type: str = ...
    tab: ChromiumBase = ...
    tab_id: str = ...
    target: str = ...
    is_failed: bool = ...
    timestamp: Optional[float] = ...
    _raw_request: Optional[dict] = ...
    _raw_response: Optional[dict] = ...
    _raw_post_data: Optional[str] = ...
    _raw_body: Optional[str] = ...
    _raw_fail_info: Optional[dict] = ...
    _base64_body: bool = ...
    _request: Optional[Request] = ...
    _response: Optional[Response] = ...
    _fail_info: Optional[FailInfo] = ...
    _resource_type: Optional[str] = ...
    _requestExtraInfo: Optional[dict] = ...
    _responseExtraInfo: Optional[dict] = ...

    def __init__(self, tab: ChromiumBase, target: Union[str, bool]):
        """
        :param tab: 产生这个数据包的ChromiumBase对象
        :param target: 监听目标
        """
        ...

    @property
    def url(self) -> str:
        """请求网址"""
        ...

    @property
    def method(self) -> str:
        """请求类型"""
        ...

    @property
    def frameId(self) -> str:
        """发出请求的frame id"""
        ...

    @property
    def resourceType(self) -> str:
        """资源类型"""
        ...

    @property
    def request(self) -> Request:
        """数据"""
        ...

    @property
    def response(self) -> Response:
        """Response数据"""
        ...

    @property
    def fail_info(self) -> Optional[FailInfo]:
        """请求失败数据"""
        ...

    def wait_extra_info(self, timeout: float = None) -> bool:
        """等待额外的信息加载完成
        :param timeout: 超时时间（秒），为None使用页面超时设置
        :return: 是否等待成功
        """
        ...

    @property
    def _request_extra_info(self) -> Optional[dict]: ...

    @property
    def _response_extra_info(self) -> Optional[dict]: ...


class Request(object):
    _data_packet: DataPacket = ...
    _request: dict = ...
    _raw_post_data: str = ...
    _postData: Union[list, dict, None, str, False] = ...

    url: str = ...
    _headers: Union[CaseInsensitiveDict, None] = ...
    method: str = ...

    urlFragment: str = ...
    hasPostData: bool = ...
    mixedContentType: Literal['blockable', 'optionally-blockable', 'none'] = ...
    initialPriority: Literal['VeryLow', 'Low', 'Medium', 'High', 'VeryHigh'] = ...
    referrerPolicy: Literal['unsafe-url', 'no-referrer-when-downgrade', 'no-referrer', 'origin',
    'origin-when-cross-origin', 'same-origin', 'strict-origin', 'strict-origin-when-cross-origin'] = ...
    isLinkPreload: bool = ...
    trustTokenParams: dict = ...
    isSameSite: bool = ...

    def __init__(self,
                 data_packet: DataPacket,
                 raw_request: dict,
                 post_data: str):
        """
        :param data_packet: DataPacket对象
        :param raw_request: 未处理的请求数据
        :param post_data: post发送的数据
        """
        ...

    @property
    def headers(self) -> dict:
        """以大小写不敏感字典返回headers数据"""
        ...

    @property
    def params(self) -> dict:
        """dict格式返回请求url中的参数"""
        ...

    @property
    def postData(self) -> Any:
        """返回postData数据"""
        ...

    @property
    def cookies(self) -> List[dict]:
        """以list形式返回发送的cookies"""
        ...

    @property
    def extra_info(self) -> Optional[RequestExtraInfo]:
        """返回额外数据"""
        ...

    @property
    def timestamp(self) -> float:
        """时间戳"""
        ...


class Response(object):
    _data_packet: DataPacket = ...
    _response: dict = ...
    _raw_body: str = ...
    _is_base64_body: bool = ...
    _body: Union[str, dict, bytes, None, list] = ...
    _headers: Union[dict, CaseInsensitiveDict, None] = ...
    _timestamp: float = ...

    url: str = ...
    status: int = ...
    statusText: str = ...
    headersText: str = ...
    mimeType: str = ...
    requestHeaders: dict = ...
    requestHeadersText: str = ...
    connectionReused: bool = ...
    connectionId = ...
    remoteIPAddress: str = ...
    remotePort: int = ...
    fromDiskCache: bool = ...
    fromServiceWorker: bool = ...
    fromPrefetchCache: bool = ...
    fromEarlyHints: bool = ...
    serviceWorkerRouterInfo: dict = ...
    encodedDataLength: int = ...
    timing: dict = ...
    serviceWorkerResponseSource: Literal['cache-storage', 'http-cache', 'fallback-code', 'network'] = ...
    responseTime: float = ...
    cacheStorageCacheName: str = ...
    protocol: str = ...
    alternateProtocolUsage: Literal['alternativeJobWonWithoutRace', 'alternativeJobWonRace', 'mainJobWonRace',
    'mappingMissing', 'broken', 'dnsAlpnH3JobWonWithoutRace', 'dnsAlpnH3JobWonRace', 'unspecifiedReason'] = ...
    securityState: Literal['unknown', 'neutral', 'insecure', 'secure', 'info', 'insecure-broken'] = ...
    securityDetails: dict = ...

    def __init__(self,
                 data_packet: DataPacket,
                 raw_response: dict,
                 raw_body: str,
                 base64_body: bool,
                 timestamp: float):
        """
        :param data_packet: DataPacket对象
        :param raw_response: 未处理的response信息
        :param raw_body: 未处理的body
        :param base64_body: body是否base64格式
        :param timestamp: 时间戳
        """
        ...

    @property
    def headers(self) -> CaseInsensitiveDict:
        """以大小写不敏感字典返回headers数据"""
        ...

    @property
    def raw_body(self) -> str:
        """返回未被处理的body文本"""
        ...

    @property
    def body(self) -> Any:
        """返回body内容，如果是json格式，自动进行转换，如果时图片格式，进行base64转换，其它格式直接返回文本"""
        ...

    @property
    def extra_info(self) -> Optional[ResponseExtraInfo]:
        """额外信息"""
        ...

    @property
    def timestamp(self) -> float:
        """时间戳"""
        ...


class ExtraInfo(object):
    _extra_info: dict = ...

    def __init__(self, extra_info: dict):
        """
        :param extra_info: dict格式信息
        """
        ...

    @property
    def all_info(self) -> dict:
        """以dict形式返回所有额外信息"""
        ...


class RequestExtraInfo(ExtraInfo):
    requestId: str = ...
    associatedCookies: List[dict] = ...
    headers: dict = ...
    connectTiming: dict = ...
    clientSecurityState: dict = ...
    siteHasCookieInOtherPartition: bool = ...


class ResponseExtraInfo(ExtraInfo):
    requestId: str = ...
    blockedCookies: List[dict] = ...
    headers: dict = ...
    resourceIPAddressSpace: str = ...
    statusCode: int = ...
    headersText: str = ...
    cookiePartitionKey: str = ...
    cookiePartitionKeyOpaque: bool = ...


class FailInfo(object):
    _data_packet: DataPacket = ...
    _fail_info: dict = ...
    errorText: str = ...
    canceled: bool = ...
    blockedReason: Optional[str] = ...
    corsErrorStatus: Optional[str] = ...

    def __init__(self, data_packet: DataPacket, fail_info: dict):
        """
        :param data_packet: DataPacket对象
        :param fail_info: 返回的失败数据
        """
        ...


class WebSocketConnectInfo(object):
    type: str = ...
    tab: ChromiumBase = ...
    tab_id: str = ...
    target: str = ...
    request_id: str = ...
    url: str = ...
    initiator: Optional[dict] = ...
    request: Optional[dict] = ...
    response: Optional[dict] = ...

    def __init__(self, tab: ChromiumBase, target: Union[str, True], request_id: str, url: str, initiator: dict = None):
        """
        :param tab: 产生这个数据包的ChromiumBase对象
        :param target: 监听目标
        :param request_id: 连接的requestId
        :param url: 连接的url
        :param initiator: 连接的发起者信息
        """
        ...


class WebSocketPacket(object):
    type: str = ...
    is_sent: bool = ...
    _raw_data: dict = ...
    _payload: Union[dict, bytes, str, None] = ...
    _connect_info: Optional[WebSocketConnectInfo] = ...
    _request_id: str = ...

    def __init__(self, tab: ChromiumBase, target: Union[str, True], raw_data: dict, is_sent: bool):
        """
        :param tab: 产生这个数据包的ChromiumBase对象
        :param target: 监听目标
        :param raw_data: 数据包数据
        :param is_sent: 是否发送
        """
        ...

    @property
    def timestamp(self) -> float:
        """时间戳"""
        ...

    @property
    def data(self) -> Union[dict, bytes, str]:
        ...

    @property
    def url(self) -> Optional[str]:
        """触发数据包的请求的url"""
        ...

    @property
    def method(self) -> None:
        """触发数据包的请求的method"""
        ...

    @property
    def frameId(self) -> str:
        """触发数据包的frame id"""
        ...

    @property
    def request(self) -> Optional[dict]:
        """连接的request信息（如有）"""
        ...

    @property
    def response(self) -> Optional[dict]:
        """连接的response信息（如有）"""
        ...

    @property
    def is_failed(self) -> bool:
        """固定为False"""
        ...


class SSEPacket(object):
    type: str = ...
    tab: ChromiumBase = ...
    tab_id: str = ...
    target: str = ...
    _raw_data: dict = ...
    _connect_info: Optional[DataPacket] = ...

    def __init__(self, tab: ChromiumBase, target: Union[str, True], raw_data: dict):
        """
        :param tab: 产生这个数据包的ChromiumBase对象
        :param target: 监听目标
        :param raw_data: 数据包数据
        """
        ...

    @property
    def timestamp(self) -> float:
        """时间戳"""
        ...

    @property
    def name(self) -> str:
        """信息名称"""
        ...

    @property
    def id(self) -> int:
        """服务器保存的id"""
        ...

    @property
    def data(self) -> str:
        """数据包数据"""
        ...

    @property
    def url(self) -> Optional[str]:
        """触发数据包的请求的url"""
        ...

    @property
    def method(self) -> None:
        """触发数据包的请求的method"""
        ...

    @property
    def frameId(self) -> str:
        """触发数据包的frame id"""
        ...

    @property
    def request(self) -> Optional[dict]:
        """连接的request信息（如有）"""
        ...

    @property
    def response(self) -> Optional[dict]:
        """连接的response信息（如有）"""
        ...

    @property
    def is_failed(self) -> bool:
        """固定为False"""
        ...


class MethodSetter(object):
    _ALLOW: set = ...
    _REMOVE: set = ...
    _ATTR: str = ...
    _listener: BaseListener = ...

    def __init__(self, listener: BaseListener): ...

    def all(self) -> MethodSetter: ...

    def GET(self, only: bool = False) -> MethodSetter: ...

    def POST(self, only: bool = False) -> MethodSetter: ...

    def PUT(self, only: bool = False) -> MethodSetter: ...

    def DELETE(self, only: bool = False) -> MethodSetter: ...

    def HEAD(self, only: bool = False) -> MethodSetter: ...

    def OPTIONS(self, only: bool = False) -> MethodSetter: ...

    def PATCH(self, only: bool = False) -> MethodSetter: ...

    def TRACE(self, only: bool = False) -> MethodSetter: ...

    def CONNECT(self, only: bool = False) -> MethodSetter: ...

    def remove_GET(self) -> MethodSetter: ...

    def remove_POST(self) -> MethodSetter: ...

    def remove_PUT(self) -> MethodSetter: ...

    def remove_DELETE(self) -> MethodSetter: ...

    def remove_HEAD(self) -> MethodSetter: ...

    def remove_OPTIONS(self) -> MethodSetter: ...

    def remove_PATCH(self) -> MethodSetter: ...

    def remove_TRACE(self) -> MethodSetter: ...

    def remove_CONNECT(self) -> MethodSetter: ...


class ResTypeSetter(object):
    _ALLOW: set = ...
    _REMOVE: set = ...
    _ATTR: str = ...
    _listener: BaseListener = ...

    def __init__(self, listener: BaseListener): ...

    def all(self) -> ResTypeSetter: ...

    def Document(self, only: bool = False) -> ResTypeSetter: ...

    def Stylesheet(self, only: bool = False) -> ResTypeSetter: ...

    def Image(self, only: bool = False) -> ResTypeSetter: ...

    def Media(self, only: bool = False) -> ResTypeSetter: ...

    def Font(self, only: bool = False) -> ResTypeSetter: ...

    def Script(self, only: bool = False) -> ResTypeSetter: ...

    def TextTrack(self, only: bool = False) -> ResTypeSetter: ...

    def XHR(self, only: bool = False) -> ResTypeSetter: ...

    def Fetch(self, only: bool = False) -> ResTypeSetter: ...

    def Prefetch(self, only: bool = False) -> ResTypeSetter: ...

    def EventSource(self, only: bool = False) -> ResTypeSetter: ...

    def WebSocket(self, only: bool = False) -> ResTypeSetter: ...

    def Manifest(self, only: bool = False) -> ResTypeSetter: ...

    def SignedExchange(self, only: bool = False) -> ResTypeSetter: ...

    def Ping(self, only: bool = False) -> ResTypeSetter: ...

    def CSPViolationReport(self, only: bool = False) -> ResTypeSetter: ...

    def Preflight(self, only: bool = False) -> ResTypeSetter: ...

    def Other(self, only: bool = False) -> ResTypeSetter: ...

    def remove_Document(self) -> ResTypeSetter: ...

    def remove_Stylesheet(self) -> ResTypeSetter: ...

    def remove_Image(self) -> ResTypeSetter: ...

    def remove_Media(self) -> ResTypeSetter: ...

    def remove_Font(self) -> ResTypeSetter: ...

    def remove_Script(self) -> ResTypeSetter: ...

    def remove_TextTrack(self) -> ResTypeSetter: ...

    def remove_XHR(self) -> ResTypeSetter: ...

    def remove_Fetch(self) -> ResTypeSetter: ...

    def remove_Prefetch(self) -> ResTypeSetter: ...

    def remove_EventSource(self) -> ResTypeSetter: ...

    def remove_WebSocket(self) -> ResTypeSetter: ...

    def remove_Manifest(self) -> ResTypeSetter: ...

    def remove_SignedExchange(self) -> ResTypeSetter: ...

    def remove_Ping(self) -> ResTypeSetter: ...

    def remove_CSPViolationReport(self) -> ResTypeSetter: ...

    def remove_Preflight(self) -> ResTypeSetter: ...

    def remove_Other(self) -> ResTypeSetter: ...

    def ws(self, only: bool = False) -> ResTypeSetter: ...

    def remove_ws(self) -> ResTypeSetter: ...

    def sse(self, only: bool = False) -> ResTypeSetter: ...

    def remove_sse(self) -> ResTypeSetter: ...


class BrowserDataPacket(object):
    tab_id: str = ...
    target: Tuple[Union[True, str], Union[True, str], Union[True, str]] = ...
    _raw_data: dict = ...
    _request: Optional[BrowserRequest] = ...
    _response: Optional[BrowserResponse] = ...
    _data: Union[None, str, list, dict] = ...

    def __init__(self,
                 tab_id: str,
                 target: Tuple[Union[True, str], Union[True, str], Union[True, str]],
                 raw_data: dict):
        ...

    @property
    def url(self) -> str:
        """返回url"""
        ...

    @property
    def method(self) -> str:
        """method类型"""
        ...

    @property
    def frameId(self) -> str:
        """产生数据包的iframe id"""
        ...

    @property
    def request(self) -> BrowserRequest:
        """返回保存request数据的对象"""
        ...

    @property
    def response(self) -> BrowserResponse:
        """返回保存response数据的对象"""
        ...

    @property
    def data(self) -> Union[None, str, list, dict]:
        """返回数据"""
        ...

    @property
    def resourceType(self) -> str:
        """返回资源类型"""
        ...

    @property
    def is_failed(self) -> bool:
        """返回是否连接失败"""
        ...

    @property
    def timestamp(self) -> None:
        """时间戳，固定返回None"""
        ...


class BrowserRequest(object):
    _request = ...
    _headers: Optional[CaseInsensitiveDict] = ...
    _postData: Union[False, None, dict, list] = ...
    method: str = ...
    hasPostData: bool = ...
    urlFragment: str = ...
    mixedContentType: dict = ...
    initialPriority: dict = ...
    referrerPolicy: str = ...
    isLinkPreload: bool = ...
    trustTokenParams: dict = ...
    isSameSite: str = ...

    def __init__(self, info: dict): ...

    def __getattr__(self, item: str): ...

    @property
    def headers(self) -> CaseInsensitiveDict:
        """以大小写不敏感字典返回headers数据"""
        ...

    @property
    def params(self) -> dict:
        """dict格式返回请求url中的参数"""
        ...

    @property
    def postData(self): ...


class BrowserResponse(object):
    headers: Optional[CaseInsensitiveDict] = ...
    statusCode: Optional[int] = ...
    statusText: Optional[str] = ...
    errorReason: Optional[str] = ...
    _raw_body: Optional[dict] = ...
    _body: Union[str, bytes, list, None] = ...

    def __init__(self, response: dict):
        ...

    @property
    def body(self) -> Union[str, bytes, list, None, dict]:
        ...
